# Generated by Django 4.1.7 on 2023-04-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ingredients', models.JSONField()),
                ('steps', models.TextField()),
                ('national', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('ischoosen', models.BooleanField(default=False)),
                ('islike', models.BooleanField(default=False)),
            ],
        ),
    ]
