# Generated by Django 4.1.7 on 2023-04-23 06:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=77)),
                ('description', models.TextField()),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), default=list, size=None)),
                ('steps', models.TextField()),
                ('national', models.CharField(max_length=22)),
                ('category', models.CharField(max_length=22)),
                ('image', models.CharField(max_length=1000)),
                ('ischoosen', models.BooleanField()),
                ('islike', models.BooleanField()),
            ],
        ),
    ]
